
# When called it will output a message and retrieve the destination thread from vichan
about_arg = "!relay"

#IRC configuration
sageru_url = "irc.sageru.org:6667"
sageru_name = "Kissu-Relay"
sageru_channel = "#qa"

#Post server destination and authentication
vichan_pipe_uri = "/tmp/virelaypipe"
vichan_post_url = "http://localhost/relaypipe.php"
verification_pass = "12345"